import React, { Component } from 'react';
import {
    Container,
    Content,
    Text,
    Card,
    Header,
    Body,
    Button,
    Title,
    CardItem,
    List,
    ListItem,
    Thumbnail,
    Left,
    Right,
    Icon,
    H1
} from 'native-base';

import {Image, PixelRatio, View} from "react-native";
import styles from "../_Global/SideBar/style";

const text =
    "==============\n" +
    "\n" +
    "Effective date: October 09, 2018\n" +
    "\n" +
    "MyWay (\"us\", \"we\", or \"our\") operates the MyWay mobile application\n" +
    "(hereinafter referred to as the \"Service\").\n" +
    "\n" +
    "This page informs you of our policies regarding the collection, use, and\n" +
    "disclosure of personal data when you use our Service and the choices you have\n" +
    "associated with that data. Our Privacy Policy is managed by the for MyWay is\n" +
    "[TermsFeed Privacy Policy Generator](https://termsfeed.com/privacy-\n" +
    "policy/generator/).\n" +
    "\n" +
    "We use your data to provide and improve the Service. By using the Service, you\n" +
    "agree to the collection and use of information in accordance with this policy.\n" +
    "Unless otherwise defined in this Privacy Policy, the terms used in this\n" +
    "Privacy Policy have the same meanings as in our Terms and Conditions.\n" +
    "\n" +
    "Definitions  \n" +
    "-----------\n" +
    "\n" +
    "  * Service\n" +
    "\n" +
    "    Service is the MyWay mobile application operated by MyWay\n" +
    "\n" +
    "  * Personal Data\n" +
    "\n" +
    "    Personal Data means data about a living individual who can be identified\n" +
    "    from those data (or from those and other information either in our\n" +
    "    possession or likely to come into our possession).\n" +
    "\n" +
    "  * Usage Data\n" +
    "\n" +
    "    Usage Data is data collected automatically either generated by the use of\n" +
    "    the Service or from the Service infrastructure itself (for example, the\n" +
    "    duration of a page visit).\n" +
    "\n" +
    "  * Cookies\n" +
    "\n" +
    "    Cookies are small files stored on your device (computer or mobile device).\n" +
    "\n" +
    "Information Collection and Use  \n" +
    "------------------------------\n" +
    "\n" +
    "We collect several different types of information for various purposes to\n" +
    "provide and improve our Service to you.\n" +
    "\n" +
    "Types of Data Collected  \n" +
    "~~~~~~~~~~~~~~~~~~~~~~~\n" +
    "\n" +
    "Personal Data  \n" +
    "*************\n" +
    "\n" +
    "While using our Service, we may ask you to provide us with certain personally\n" +
    "identifiable information that can be used to contact or identify you\n" +
    "(\"Personal Data\"). Personally identifiable information may include, but is not\n" +
    "limited to:\n" +
    "\n" +
    "  * Email address\n" +
    "  * Address, State, Province, ZIP/Postal code, City\n" +
    "  * Cookies and Usage Data\n" +
    "\n" +
    "Usage Data  \n" +
    "**********\n" +
    "\n" +
    "When you access the Service by or through a mobile device, we may collect\n" +
    "certain information automatically, including, but not limited to, the type of\n" +
    "mobile device you use, your mobile device unique ID, the IP address of your\n" +
    "mobile device, your mobile operating system, the type of mobile Internet\n" +
    "browser you use, unique device identifiers and other diagnostic data (\"Usage\n" +
    "Data\").\n" +
    "\n" +
    "Tracking &amp; Cookies Data  \n" +
    "************\n" +
    "\n" +
    "We use cookies and similar tracking technologies to track the activity on our\n" +
    "Service and we hold certain information.\n" +
    "\n" +
    "Cookies are files with a small amount of data which may include an anonymous\n" +
    "unique identifier. Cookies are sent to your browser from a website and stored\n" +
    "on your device. Other tracking technologies are also used such as beacons,\n" +
    "tags and scripts to collect and track information and to improve and analyse\n" +
    "our Service.\n" +
    "\n" +
    "You can instruct your browser to refuse all cookies or to indicate when a\n" +
    "cookie is being sent. However, if you do not accept cookies, you may not be\n" +
    "able to use some portions of our Service.\n" +
    "\n" +
    "Examples of Cookies we use:\n" +
    "\n" +
    "  * Session Cookies. We use Session Cookies to operate our Service.\n" +
    "  * Preference Cookies. We use Preference Cookies to remember your preferences\n" +
    "    and various settings.\n" +
    "  * Security Cookies. We use Security Cookies for security purposes.\n" +
    "\n" +
    "Use of Data  \n" +
    "-----------\n" +
    "\n" +
    "MyWay uses the collected data for various purposes:\n" +
    "\n" +
    "  * To provide and maintain the Service\n" +
    "  * To notify you about changes to our Service\n" +
    "  * To allow you to participate in interactive features of our Service when\n" +
    "    you choose to do so\n" +
    "  * To provide customer care and support\n" +
    "  * To provide analysis or valuable information so that we can improve the\n" +
    "    Service\n" +
    "  * To monitor the usage of the Service\n" +
    "  * To detect, prevent and address technical issues\n" +
    "\n" +
    "Transfer Of Data  \n" +
    "----------------\n" +
    "\n" +
    "Your information, including Personal Data, may be transferred to — and\n" +
    "maintained on — computers located outside of your state, province, country or\n" +
    "other governmental jurisdiction where the data protection laws may differ than\n" +
    "those from your jurisdiction.\n" +
    "\n" +
    "If you are located outside Canada and choose to provide information to us,\n" +
    "please note that we transfer the data, including Personal Data, to Canada and\n" +
    "process it there.\n" +
    "\n" +
    "Your consent to this Privacy Policy followed by your submission of such\n" +
    "information represents your agreement to that transfer.\n" +
    "\n" +
    "MyWay will take all steps reasonably necessary to ensure that your data is\n" +
    "treated securely and in accordance with this Privacy Policy and no transfer of\n" +
    "your Personal Data will take place to an organization or a country unless\n" +
    "there are adequate controls in place including the security of your data and\n" +
    "other personal information.\n" +
    "\n" +
    "Disclosure Of Data  \n" +
    "------------------\n" +
    "\n" +
    "Legal Requirements  \n" +
    "~~~~~~~~~~~~~~~~~~\n" +
    "\n" +
    "MyWay may disclose your Personal Data in the good faith belief that such\n" +
    "action is necessary to:\n" +
    "\n" +
    "  * To comply with a legal obligation\n" +
    "  * To protect and defend the rights or property of MyWay\n" +
    "  * To prevent or investigate possible wrongdoing in connection with the\n" +
    "    Service\n" +
    "  * To protect the personal safety of users of the Service or the public\n" +
    "  * To protect against legal liability\n" +
    "\n" +
    "Security of Data  \n" +
    "----------------\n" +
    "\n" +
    "The security of your data is important to us but remember that no method of\n" +
    "transmission over the Internet or method of electronic storage is 100% secure.\n" +
    "While we strive to use commercially acceptable means to protect your Personal\n" +
    "Data, we cannot guarantee its absolute security.\n" +
    "\n" +
    "Service Providers  \n" +
    "-----------------\n" +
    "\n" +
    "We may employ third party companies and individuals to facilitate our Service\n" +
    "(\"Service Providers\"), to provide the Service on our behalf, to perform\n" +
    "Service-related services or to assist us in analyzing how our Service is used.\n" +
    "\n" +
    "These third parties have access to your Personal Data only to perform these\n" +
    "tasks on our behalf and are obligated not to disclose or use it for any other\n" +
    "purpose.\n" +
    "\n" +
    "Analytics  \n" +
    "~~~~~~~~~\n" +
    "\n" +
    "We may use third-party Service Providers to monitor and analyze the use of our\n" +
    "Service.\n" +
    "\n" +
    "  * Piwik / Matomo\n" +
    "\n" +
    "    Piwik or Matomo is a web analytics service. You can visit their Privacy\n" +
    "    Policy page here: <https://matomo.org/privacy-policy>\n" +
    "\n" +
    "  * Clicky\n" +
    "\n" +
    "    Clicky is a web analytics service. Read the Privacy Policy for Clicky\n" +
    "    here: <https://clicky.com/terms>\n" +
    "\n" +
    "  * Unity Analytics\n" +
    "\n" +
    "    Unity Analytics is provided by Unity Technologies.\n" +
    "\n" +
    "    For more information on what type of information Unity Analytics collects,\n" +
    "    please visit their Privacy Policy page: [hhttps://unity3d.com/legal\n" +
    "    /privacy-policy](https://unity3d.com/legal/privacy-policy)\n" +
    "\n" +
    "Links to Other Sites  \n" +
    "--------------------\n" +
    "\n" +
    "Our Service may contain links to other sites that are not operated by us. If\n" +
    "you click a third party link, you will be directed to that third party's site.\n" +
    "We strongly advise you to review the Privacy Policy of every site you visit.\n" +
    "\n" +
    "We have no control over and assume no responsibility for the content, privacy\n" +
    "policies or practices of any third party sites or services.\n" +
    "\n" +
    "Children's Privacy  \n" +
    "------------------\n" +
    "\n" +
    "Our Service does not address anyone under the age of 18 (\"Children\").\n" +
    "\n" +
    "We do not knowingly collect personally identifiable information from anyone\n" +
    "under the age of 18. If you are a parent or guardian and you are aware that\n" +
    "your Child has provided us with Personal Data, please contact us. If we become\n" +
    "aware that we have collected Personal Data from children without verification\n" +
    "of parental consent, we take steps to remove that information from our\n" +
    "servers.\n" +
    "\n" +
    "Changes to This Privacy Policy  \n" +
    "------------------------------\n" +
    "\n" +
    "We may update our Privacy Policy from time to time. We will notify you of any\n" +
    "changes by posting the new Privacy Policy on this page.\n" +
    "\n" +
    "We will let you know via email and/or a prominent notice on our Service, prior\n" +
    "to the change becoming effective and update the \"effective date\" at the top of\n" +
    "this Privacy Policy.\n" +
    "\n" +
    "You are advised to review this Privacy Policy periodically for any changes.\n" +
    "Changes to this Privacy Policy are effective when they are posted on this\n" +
    "page.\n" +
    "\n" +
    "Contact Us  \n" +
    "----------\n" +
    "\n" +
    "If you have any questions about this Privacy Policy, please contact us:\n" +
    "\n" +
    "  * By visiting this page on our website: http://www.niuvisioncanada.com/cn\n" +
    "    /privacy-policy.html\n" +
    "\n";
class UserAgreementScreen extends Component{

    render(){
        console.log(this.props.count);
        return(
            <Container>
                <Header>
                    <Left>
                        <Button transparent onPress={() => this.props.navigation.goBack()}>
                            <Icon name="arrow-back" />
                        </Button>
                    </Left>
                    <Body>
                    <Title>用户使用协议</Title>
                    </Body>
                    <Right />
                </Header>
                <Content style={{backgroundColor:"#eaeaea"}}>
                    <View style={{marginLeft:6,marginRight:6}}>
                        <H1>Privacy Policy</H1>
                        <Text>
                            {text}
                        </Text>
                    </View>
                </Content>
            </Container>
        );
    }
}

export default (UserAgreementScreen);
